version: '3.8'

services:
  db:
    container_name: postgres-pet-basics-30
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - my-vol:/var/lib/docker/volumes/my-vol/_data
    ports:
        - '${TYPEORM_PORT}:${TYPEORM_PORT}'
  backend:
    container_name: backend-nest-postgres-3
    build:
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db

volumes:
  my-vol:
    external: true

